# Site settings
title: Acid Rays 
tagline: ""
# baseurl: "/erg-dossier-2022" 
url: http://localhost
baseurl: /

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

collections_dir: projects
collections:
    landing:
      sort_by: id
      output: true
    commercials:
      sort_by: id
      output: true
    special_projects:
      sort_by: id
      output: true
    innovation:
      sort_by: id
      output: true
